### ISSUE TITLE
低版本浏览器兼容问题——页面堆叠在一起

### ISSUE THREAD

**Issue by growdu** [KwokKwok/slide-lab#2]
使用的谷歌浏览器内核版本较低，用的是106.0.5249，发现页面都是堆叠在中间，无法使用，有没有什么方式可以适配兼容一下。不太想升级浏览器。

**Comment by KwokKwok** [comment]
嗨，清除缓存刷新页面重试一下检查一下是否正常

**Comment by growdu** [comment]
我把这个新的提交试了一下，发现还是一样的，

**Comment by KwokKwok** [comment]
操作系统版本发一下，我尽量看一下

**Comment by KwokKwok** [comment]
根据我在 106 上的测试，应该是已经调整好了。看你后一个 issue 截图也是正确的，我这边关闭这个 issue 了
