### ISSUE TITLE
添加项目能不能再多一个颜色——四象限刚好对应4种颜色，当然如果能自定义添加项目，自定义颜色最好

### ISSUE THREAD

**Issue by growdu** [KwokKwok/slide-lab#3]
添加项目能不能再多个一个颜色——四象限刚好对应4种颜色，当然如果能自定义添加项目，自定义颜色最好

**Comment by KwokKwok** [comment]
不太理解，截图说明一下你想改什么吧？

**Comment by growdu** [comment]
![image](https://github.com/user-attachments/assets/2711a506-286e-4182-80c8-2539402bfda8)
这里再添加一个颜色。

**Comment by KwokKwok** [comment]
右键可以添加分类、编辑分类颜色

**Comment by growdu** [comment]
ok。
