### ISSUE TITLE
请问下如何新增滑块

### ISSUE THREAD

**Issue by FlappyROC** [KwokKwok/slide-lab#4]
可以针对滑块进行删除、拖动、编辑；但是找不到如何新增一个滑块的操作，希望作者解答一下。

**Comment by KwokKwok** [comment]
<img width="754" alt="image" src="https://github.com/user-attachments/assets/70b4434b-97dd-4914-a940-dda9e02ae89f">

在底部的分类上右键，可以新增项目

也可以编辑或者新增大的分类
